cmake_minimum_required(VERSION 3.6)
project(mkxp-sunshine)
set(SDL_DISKAUDIO OFF)
set(SDL_DUMMYAUDIO OFF)
set(SDL_DUMMYCAMERA OFF)
set(SDL_DUMMYVIDEO OFF)
set(SDL_VIRTUAL_JOYSTICK OFF)
set(SDL_TRAY OFF)
set(SDL_CAMERA OFF)
set(SDL_NOTIFICATION OFF)
set(SDL_POWER OFF)
add_subdirectory(SDL)
add_subdirectory(SDL_image)
add_subdirectory(SDL_mixer)
add_subdirectory(SDL_ttf)
add_subdirectory(SDL_net)
add_subdirectory(mkxp-sunshine)
