cmake_minimum_required(VERSION 3.6)
project(mkxp-sunshine)
set(SDL_TESTS OFF)
set(SDL_TEST_LIBRARY OFF)
set(SDL_DISKAUDIO OFF)
set(SDL_DUMMYAUDIO OFF)
set(SDL_DUMMYCAMERA OFF)
set(SDL_DUMMYVIDEO OFF)
set(SDL_EXAMPLES OFF)
set(SDL_TESTS OFF)
set(SDL_VIRTUAL_JOYSTICK OFF)
set(SDL_TRAY OFF)
set(SDL_CAMERA OFF)
set(SDL_NOTIFICATION OFF)
set(SDL_POWER OFF)
set(SDLNET_SAMPLES OFF)
set(SDLTTF_SAMPLES OFF)
set(SDLMIXER_TESTS OFF)
set(SDLMIXER_EXAMPLES OFF)
set(SDL_SHARED OFF)
set(SDL_STATIC ON)
add_subdirectory(SDL)
add_subdirectory(SDL_image)
add_subdirectory(SDL_mixer)
add_subdirectory(SDL_ttf)
add_subdirectory(SDL_net)
add_subdirectory(mkxp-sunshine)
