include(CheckCXXCompilerFlag)
include(CheckCCompilerFlag)
include(CheckLinkerFlag)

# Helper for checking if options supported by compiller
function(check_option output_var)
    set(CMAKE_REQUIRED_QUIET TRUE)
    set(result)
    foreach(option IN LISTS ARGN)
        string(MAKE_C_IDENTIFIER "${option}" option_id)
        set(check_var "HAVE_OPTION_${option_id}")
        unset(${check_var} CACHE)

        check_cxx_compiler_flag("${option}" "${check_var}")
        if(${check_var})
            message(STATUS "${option} supported")
            list(APPEND result "${option}")
        else()
			set(check_var_c "HAVE_OPTION_C_${option_id}")
			unset(${check_var_c} CACHE)
        	check_c_compiler_flag("${option}" "${check_var_c}")
        	if(${check_var_c})
        	    message(STATUS "${option} supported")
        	    list(APPEND result "${option}")
        	else()
        	    message(STATUS "${option} unsupported")
        	endif()
        endif()
    endforeach()

    set("${output_var}" "${result}" PARENT_SCOPE)
    set(CMAKE_REQUIRED_QUIET FALSE)
endfunction()

function(check_linker_option output_var)
    set(CMAKE_REQUIRED_QUIET TRUE)
    set(result)

    foreach(option IN LISTS ARGN)
        string(MAKE_C_IDENTIFIER "${option}" option_id)
        set(check_var "HAVE_OPTION_${option_id}")

        check_linker_flag(CXX "${option}" "${check_var}")
        if(${check_var})
            message(STATUS "${option} supported")
            list(APPEND result "${option}")
        else()
			message(STATUS "${option} unsupported")
        endif()
    endforeach()

    set("${output_var}" "${result}" PARENT_SCOPE)
    set(CMAKE_REQUIRED_QUIET FALSE)
endfunction()
